# Generated by Django 4.1.2 on 2022-10-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=200)),
                ("password", models.CharField(max_length=10)),
                ("birthday", models.DateField()),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("balance", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Transations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wasDeposit", models.BooleanField()),
                ("wasWithdraw", models.BooleanField()),
                ("wasMbway", models.BooleanField()),
                ("wasCard", models.BooleanField()),
                ("amount", models.FloatField()),
                ("datetime", models.DateTimeField()),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
            ],
        ),
    ]
