# Generated by Django 4.1.2 on 2022-11-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_game_id'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promo_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('value_restriction', models.FloatField()),
                ('mail_template_path', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=200)),
                ('limit_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Deposit_Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.FloatField()),
                ('usages', models.IntegerField()),
                ('first_deposit_restriction', models.BooleanField()),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Bet_Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField()),
                ('applyable_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.promotion')),
            ],
        ),
    ]
