# Generated by Django 4.1.2 on 2022-10-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_payment_methods_transation_delete_transations"),
    ]

    operations = [
        migrations.RenameModel(old_name="Payment_methods", new_name="Payment_method",),
    ]
