# Generated by Django 4.1.2 on 2022-10-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_payment_methods_payment_method"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment_method", name="id",),
        migrations.AlterField(
            model_name="payment_method",
            name="method",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="transation",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
