# Generated by Django 4.1.2 on 2022-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bet_promotion_applyable_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image_path',
            field=models.ImageField(upload_to='promotions/images'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='mail_template_path',
            field=models.FileField(upload_to='promotions/template'),
        ),
    ]
