# Generated by Django 4.1.2 on 2022-12-01 11:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_promotion_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='image_path',
            field=models.ImageField(storage=accounts.models.OverwriteStorage(), upload_to='promotions/images'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='mail_template_path',
            field=models.FileField(storage=accounts.models.OverwriteStorage(), upload_to='promotions/template'),
        ),
    ]
