# Generated by Django 4.1.2 on 2022-10-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session", old_name="userID", new_name="user_in_session",
        ),
    ]
