# Generated by Django 4.1.2 on 2022-12-02 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_participant_odd_number_betters_alter_game_away_and_more'),
        ('accounts', '0005_alter_promotion_image_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteParticipants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCompetitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
