# Generated by Django 4.1.2 on 2022-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='currency',
            field=models.CharField(default='€', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='language',
            field=models.CharField(default='en', max_length=10),
            preserve_default=False,
        ),
    ]
