# Generated by Django 4.1.2 on 2022-11-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Ad',
        ),
    ]
