# Generated by Django 4.1.2 on 2022-12-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_participant_odd_number_betters_alter_game_away_and_more'),
        ('accounts', '0009_followedgames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedgames',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
