# Generated by Django 4.1.2 on 2022-11-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_ad_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('specID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
