# Generated by Django 4.1.2 on 2022-11-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('betID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('datetime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet_status',
            fields=[
                ('status', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Bet_status',
            },
        ),
        migrations.CreateModel(
            name='Bet_type',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bet_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd', models.FloatField()),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamble.bet')),
                ('odd_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.odd')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamble.bet_status')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamble.bet_status'),
        ),
        migrations.AddField(
            model_name='bet',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamble.bet_type'),
        ),
    ]
