# Generated by Django 4.1.2 on 2022-10-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
        ("gamble", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bet_game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gamble.bet"
                    ),
                ),
                (
                    "odd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.odd"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="History",),
    ]
