# Generated by Django 4.1.2 on 2022-11-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
