# Generated by Django 4.1.2 on 2022-11-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamble", "0002_bet_game_delete_history"),
    ]

    operations = [
        migrations.RemoveField(model_name="bet", name="total_odd",),
    ]
