# Generated by Django 4.1.2 on 2022-11-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_rename_sate_game_state"),
        ("gamble", "0003_remove_bet_total_odd"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet_game",
            name="odd_id",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="game.odd"
            ),
        ),
        migrations.AlterField(
            model_name="bet_game", name="odd", field=models.FloatField(),
        ),
    ]
