# Generated by Django 4.1.2 on 2022-10-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
                ("home", models.CharField(max_length=50)),
                ("away", models.CharField(max_length=50)),
                ("home_score", models.IntegerField()),
                ("away_score", models.IntegerField()),
                ("datetime", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Odd_type",
            fields=[
                (
                    "type",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sports",
            fields=[
                (
                    "sport",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("has_draw", models.BooleanField()),
                ("is_team_sport", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "state",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Odd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odd", models.FloatField()),
                ("happened", models.BooleanField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.game"
                    ),
                ),
                (
                    "odd_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.odd_type"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="sate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.state"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.sports"
            ),
        ),
    ]
