# Generated by Django 4.1.2 on 2022-11-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
