# Generated by Django 4.1.2 on 2022-10-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Sports", new_name="Sport",),
        migrations.AlterField(
            model_name="game", name="away_score", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="game", name="home_score", field=models.IntegerField(default=0),
        ),
    ]
