# Generated by Django 4.1.2 on 2022-10-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_sports_sport_alter_game_away_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="odd", name="happened", field=models.BooleanField(default=False),
        ),
    ]
