# Generated by Django 4.1.2 on 2022-11-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_game_datetime_alter_game_game_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "country",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "competition",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.country"
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.sport"
                    ),
                ),
            ],
        ),
    ]
