# Generated by Django 4.1.2 on 2022-11-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_country_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="competition",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.competition",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="country",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.country",
            ),
            preserve_default=False,
        ),
    ]
