# Generated by Django 4.1.2 on 2022-11-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_competition_game_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='sate',
            new_name='state',
        ),
    ]
